In [1]:
import pandas as pd

def pdb_to_df(file_name):
    df = pd.DataFrame(columns = ['Protein_Num','Protein_Name','Cite_Name','x_coord','y_coord','z_coord'])
    with open(file_name, 'r') as file:
        index = 0
        for line in file.readlines():
            line = line.split(' ')
            if line[0] == 'ATOM':
                info = []
                for i in line:
                    if i != '':
                        info.append(i)
                df.loc[index, 'Protein_Num'] = int(info[4])
                df.loc[index, 'Protein_Name'] = info[3]
                df.loc[index, 'Cite_Name'] = info[2]
                df.loc[index, 'x_coord'] = float(info[5])
                df.loc[index, 'y_coord'] = float(info[6])
                df.loc[index, 'z_coord'] = float(info[7])
            index += 1
        df = df.dropna()
        df = df.drop(index = df[(df.Cite_Name == 'COM')].index.tolist())
        df = df.reset_index(drop = True)
    return df

pdb_df = pdb_to_df('999999.pdb')
pdb_df

    Protein_Num Protein_Name Cite_Name  x_coord  y_coord  z_coord
0             1            A       dbd  153.338  104.161    181.2
1             1            A       mbs  158.708  105.519  179.946
2             1            A       dbs  156.453  100.884  179.227
3             2            A       dbd   920.76  185.442   141.21
4             2            A       mbs  917.582  187.373  145.502
..          ...          ...       ...      ...      ...      ...
616         295            F        bs  791.263    100.0    100.0
617         296            F        bs  667.754    100.0    100.0
618         297            F        bs  416.272    100.0    100.0
619         298            F        bs  213.925    100.0    100.0
620         299            F        bs  240.468    100.0    100.0

[621 rows x 6 columns]

In [2]:
def dis_cal(x, y):
    return ((x[0]-y[0])**2+(x[1]-y[1])**2+(x[2]-y[2])**2)**0.5

dis_cal([1,1,1], [0,0,0])

1.7320508075688772

In [3]:
binding_info = pd.DataFrame(columns = ['Protein_Name_1','Cite_Name_1','Protein_Name_2','Cite_Name_2','sigma'])
binding_info.loc[0] = ['A','dbd','F','bs',1.0]
binding_info.loc[1] = ['A','mbs','A','mbs',1.0]
binding_info.loc[2] = ['A','dbs','A','dbs',1.0]

binding_info

  Protein_Name_1 Cite_Name_1 Protein_Name_2 Cite_Name_2  sigma
0              A         dbd              F          bs    1.0
1              A         mbs              A         mbs    1.0
2              A         dbs              A         dbs    1.0

In [ ]:
def dis_df_gen(df, info):
    dis_df = pd.DataFrame(columns = ['Protein_Num_1','Protein_Name_1','Cite_Name_1','Protein_Num_2','Protein_Name_2','Cite_Name_2','sigma','dis'])
    index = 0
    for i in range(len(info)):
        df_temp_1 = df[df['Protein_Name'].isin([info.iloc[i, 0]])]
        df_1 = df_temp_1[df_temp_1['Cite_Name'].isin([info.iloc[i, 1]])]
        df_temp_2 = df[df['Protein_Name'].isin([info.iloc[i, 2]])]
        df_2 = df_temp_2[df_temp_2['Cite_Name'].isin([info.iloc[i, 3]])]
        df_1 = df_1.reset_index(drop = True)
        df_2 = df_2.reset_index(drop = True)
        print(df_1)
        print(df_2)
        
        for j in range(len(df_1)):
            for k in range(len(df_2)):
                dis_df.loc[index, 'Protein_Num_1'] = df_1.loc[j, 'Protein_Num']
                dis_df.loc[index, 'Protein_Name_1'] = df_1.loc[j, 'Protein_Name']
                dis_df.loc[index, 'Cite_Name_1'] = df_1.loc[j, 'Cite_Name']
                dis_df.loc[index, 'Protein_Num_2'] = df_2.loc[k, 'Protein_Num']
                dis_df.loc[index, 'Protein_Name_2'] = df_2.loc[k, 'Protein_Name']
                dis_df.loc[index, 'Cite_Name_2'] = df_2.loc[k, 'Cite_Name']
                dis_df.loc[index, 'sigma'] = info.loc[i, 'sigma']
                x = [df_1.loc[j, 'x_coord'], df_1.loc[j, 'y_coord'], df_1.loc[j, 'z_coord']]
                y = [df_2.loc[k, 'x_coord'], df_2.loc[k, 'y_coord'], df_2.loc[k, 'z_coord']]
                dis_df.loc[index, 'dis'] = dis_cal(x, y)
                index += 1

    return dis_df

dis_df = dis_df_gen(df = pdb_df, info = binding_info)

    Protein_Num Protein_Name Cite_Name  x_coord  y_coord  z_coord
0             1            A       dbd  153.338  104.161    181.2
1             2            A       dbd   920.76  185.442   141.21
2             3            A       dbd  890.711   76.038   56.269
3             4            A       dbd  746.734   99.035  100.101
4             5            A       dbd   984.99   99.315   99.308
..          ...          ...       ...      ...      ...      ...
174         194            A       dbd  231.573  117.389   101.96
175         195            A       dbd  675.418   99.898  100.931
176         197            A       dbd    97.38   78.468   55.042
177         198            A       dbd  171.425   72.303   79.117
178         199            A       dbd  109.352    94.17   58.219

[179 rows x 6 columns]
   Protein_Num Protein_Name Cite_Name  x_coord y_coord z_coord
0          202            F        bs  489.153   100.0   100.0
1          203            F        bs   172.94   100.0   100.0
2          204            F        bs  183.651   100.0   100.0
3          205            F        bs  861.158   100.0   100.0
4          206            F        bs  228.933   100.0   100.0
..         ...          ...       ...      ...     ...     ...
79         295            F        bs  791.263   100.0   100.0
80         296            F        bs  667.754   100.0   100.0
81         297            F        bs  416.272   100.0   100.0
82         298            F        bs  213.925   100.0   100.0
83         299            F        bs  240.468   100.0   100.0

[84 rows x 6 columns]
    Protein_Num Protein_Name Cite_Name  x_coord  y_coord  z_coord
0             1            A       mbs  158.708  105.519  179.946
1             2            A       mbs  917.582  187.373  145.502
2             3            A       mbs  891.006   70.408   56.952
3             4            A       mbs  743.517   94.355  100.137
4             5            A       mbs   979.82   99.347   96.959
..          ...          ...       ...      ...      ...      ...
174         194            A       mbs  233.037  111.917  101.555
175         195            A       mbs   673.73   100.38    95.53
176         197            A       mbs     99.8   83.509   54.054
177         198            A       mbs  171.765   73.409   84.677
178         199            A       mbs  105.487   90.968   55.563

[179 rows x 6 columns]
    Protein_Num Protein_Name Cite_Name  x_coord  y_coord  z_coord
0             1            A       mbs  158.708  105.519  179.946
1             2            A       mbs  917.582  187.373  145.502
2             3            A       mbs  891.006   70.408   56.952
3             4            A       mbs  743.517   94.355  100.137
4             5            A       mbs   979.82   99.347   96.959
..          ...          ...       ...      ...      ...      ...
174         194            A       mbs  233.037  111.917  101.555
175         195            A       mbs   673.73   100.38    95.53
176         197            A       mbs     99.8   83.509   54.054
177         198            A       mbs  171.765   73.409   84.677
178         199            A       mbs  105.487   90.968   55.563

[179 rows x 6 columns]

In [ ]:
dis_df

In [ ]:
def bind_df_gen(dis_df, buffer_ratio):
    bind_df = pd.DataFrame(columns = ['Protein_Num_1','Protein_Name_1','Cite_Name_1','Protein_Num_2','Protein_Name_2','Cite_Name_2','sigma','dis'])
    index = 0
    for i in range(len(dis_df)):
        if dis_df.loc[i, 'dis'] >= dis_df.loc[i, 'sigma']*(1-buffer_ratio):
            if dis_df.loc[i, 'dis'] <= dis_df.loc[i, 'sigma']*(1+buffer_ratio):
                bind_df.loc[index] = dis_df.loc[i]
                index += 1
    return bind_df

bind_df = bind_df_gen(dis_df, buffer_ratio = 0.01)
bind_df

In [ ]:
def find_bond(bind_df):
    bond_lst = []
    for i in range(len(bind_df)):
        bond_lst.append([int(bind_df.loc[i, 'Protein_Num_1']), int(bind_df.loc[i, 'Protein_Num_2'])])
    for i in bond_lst:
        i.sort()
    bond_lst_ = []
    for i in bond_lst:
        if i not in bond_lst_:
            bond_lst_.append(i)
    return bond_lst_

bond_lst = find_bond(bind_df)
print(bond_lst)

In [ ]:
def find_complex(pdb_df, bond_lst):
    complex_lst = []
    for i in range(1, 1+pdb_df['Protein_Num'].max()):
        complex_temp = [i]
        j = 0
        while j < len(bond_lst):
            if bond_lst[j][0] in complex_temp and bond_lst[j][1] not in complex_temp:
                complex_temp.append(bond_lst[j][1])
                j = 0
            elif bond_lst[j][1] in complex_temp and bond_lst[j][0] not in complex_temp:
                complex_temp.append(bond_lst[j][0])
                j = 0
            else:
                j += 1
        complex_lst.append(complex_temp)
    for i in complex_lst:
        i.sort()
    complex_lst_ = []
    for i in complex_lst:
        if i not in complex_lst_:
            complex_lst_.append(i)       
    return complex_lst_


complex_lst = find_complex(pdb_df, bond_lst)
print(complex_lst)

In [ ]:
def complex_df_gen(pdb_df, complex_lst):
    name_lst = list(pdb_df['Protein_Name'])
    name_lst_ = []
    for i in name_lst:
        if i not in name_lst_:
            name_lst_.append(i)
    column_lst = []
    for i in name_lst_:
        column_lst.append(i)
    column_lst.append('Protein_Num')
    complex_df = pd.DataFrame(columns = column_lst)
    index = 0
    for i in complex_lst:
        complex_df.loc[index] = 0
        complex_df.loc[index,'Protein_Num'] = str(i)
        for j in i:
            for indexs in pdb_df.index: 
                for k in range(len(pdb_df.loc[indexs].values)): 
                    if(pdb_df.loc[indexs].values[k] == j): 
                        col = pdb_df.loc[indexs,'Protein_Name']
                        complex_df.loc[index,col] += 1
                        break
                else:
                    continue
                break
        index += 1 
    return complex_df
    
complex_df = complex_df_gen(pdb_df, complex_lst)